Add snyk (#28)
* Add snyk to the flow

* Snyk auth token add

* Circle orb add to snyk

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

* Fix snyk auth token var name

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,8 @@
 version: 2.1
 
+orbs:
+  snyk: snyk/snyk@2.2.0
+
 executors:
   java-docker:
     docker:
@@ -80,19 +83,53 @@ jobs:
             VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
             VERSION=${VERSION:-1.0.0}  # Use default version 1.0.0 if empty
             echo "Using version: $VERSION"
-            echo "VERSION=$VERSION" >> version.env
+            mkdir -p workspace
+            echo "VERSION=$VERSION" >> workspace/version.env
       - run:
           name: Build Docker Image
           command: |
-            source version.env
+            source workspace/version.env
             docker build --build-arg VERSION=$VERSION -t ${DOCKER_USERNAME}/jcraft-userman:$VERSION .
       - run:
           name: Push Docker Image
           command: |
-            source version.env
+            source workspace/version.env
             echo "Pushing image: ${DOCKER_USERNAME}/jcraft-userman:$VERSION"
             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
             docker push ${DOCKER_USERNAME}/jcraft-userman:$VERSION
+      - persist_to_workspace:
+          root: workspace
+          paths:
+            - version.env
+
+  snyk-scan:
+    executor: docker-executor
+    steps:
+      - checkout
+      - attach_workspace:
+          at: workspace
+      - setup_remote_docker:
+          docker_layer_caching: true
+      - run:
+          name: Load Version
+          command: |
+            if [ ! -f workspace/version.env ]; then
+              echo "Error: version.env not found in workspace"
+              ls -la workspace/
+              exit 1
+            fi
+            source workspace/version.env
+            echo "VERSION=$VERSION" >> $BASH_ENV
+            source $BASH_ENV
+            echo "Loaded version: $VERSION"
+      - run:
+          name: Pull Docker Image
+          command: |
+            docker pull ${DOCKER_USERNAME}/jcraft-userman:$VERSION
+      - snyk/scan:
+          token-variable: SNYK_TOKEN
+          docker-image-name: "${DOCKER_USERNAME}/jcraft-userman:$VERSION"
+          target-file: "Dockerfile"
 
   deploy-develop:
     executor: base-executor
@@ -142,9 +179,17 @@ workflows:
             branches:
               only:
                 - develop
+      - snyk-scan:
+          requires:
+            - docker-build
+          filters:
+            branches:
+              only:
+                - develop
       - deploy-develop:
           requires:
             - docker-build
+            - snyk-scan
           filters:
             branches:
               only:
